services:
  # 后端服务 - 本地开发模式
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://financial_user:financial_password@localhost:5432/financial_db
      - REDIS_URL=redis://localhost:6379
      - JWT_SECRET=your-super-secret-jwt-key
      - PORT=8000
    network_mode: host

  # 前端服务 - 本地开发模式
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENV=development
    network_mode: host 