services:
  # PostgreSQL 数据库 - 使用具体版本
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=financial_db
      - POSTGRES_USER=financial_user
      - POSTGRES_PASSWORD=financial_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - financial-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financial_user -d financial_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis 缓存 - 使用最新稳定版本
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - financial-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 后端服务 - 使用本地构建
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-super-secret-jwt-key-123456789
      - PORT=8000
    networks:
      - financial-net
    restart: unless-stopped

  # 前端服务 - 使用本地构建
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_API_VERSION=v1
    depends_on:
      - backend
    networks:
      - financial-net
    restart: unless-stopped

  # pgAdmin (数据库管理工具) - 暂时禁用
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@financial.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin123
  #     - PGADMIN_CONFIG_SERVER_MODE=False
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - financial-net

volumes:
  postgres_data:
  redis_data:

networks:
  financial-net:
    driver: bridge
